version: '3'
services:
  zookeeper-1:
    image: wurstmeister/zookeeper
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"  

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    depends_on:
      - zookeeper-1
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: PLAINTEXT://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    container_name: kibana
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "5601:5601"
    expose:
      - 5601

  weatherapi:
    image: weatherapi_image:0.9
    container_name: weatherapi
    ports:
      - 8081:5000
    expose:
      - 5000

volumes:
  data01:
    driver: local